# Deployment configuration
app1:
  replicaCount: 1
  image:
    repository: wmadiano/demojwt
    tag: latest
    pullPolicy: Always
  nameOverride: ""
  fullnameOverride: ""
  containerPort: 3000
  app:
    name: api01

app2:
  replicaCount: 1
  image:
    repository: wmadiano/reactjsweb02-demo
    tag: latest
    pullPolicy: Always
  nameOverride: ""
  fullnameOverride: ""
  containerPort: 80
  app:
    name: proto1-fe


# Service configuration
service1:
  service:
    name: api01-service
    app: api01
    type: ClusterIP
    port: 80
    targetPort: 3000
    protocol: TCP

service2:
  service:
    name: proto1-fe-service
    app: proto1-fe
    type: ClusterIP
    port: 80
    targetPort: 80
    protocol: TCP


# Ingress configuration
ingress:
  enabled: true
  name: my-service-ingress
  className: "" # Specify if needed
  hosts:
    - host: api.gresdev.com
      paths:
        - path: /
          pathType: Prefix
          service:
            name: api01-service
            port: 80
    - host: web.gresdev.com
      paths:
        - path: /
          pathType: Prefix
          service:
            name: proto1-fe-service
            port: 80