apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-service-ingress
  # Since className is empty, no annotations for ingress.class
spec:
  # Since className is empty, no ingressClassName is set
  rules:
  - host: web.gresdev.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: proto1-fe-service
            port:
              number: 80
  - host: api2.gresdev.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: api02-service
            port:
              number: 80
