{{- range $key, $value := .Values.services }}
{{- if $value.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $value.name }}
spec:
  type: {{ $value.type }}
  selector:
    app: {{ $value.app }}
  ports:
    - protocol: {{ $value.protocol }}
      port: {{ $value.port }}
      targetPort: {{ $value.targetPort }}
---
{{- end }}
{{- end }}
