apiVersion: v1
kind: Service
metadata:
  name: proto1-fe-service-np
spec:
  type: NodePort
  selector:
    app: proto1-fe # Replace with your application selector
  ports:
  - protocol: TCP
    port: 80 # Service port
    targetPort: 80 # Application container port
    nodePort: 30001 # Choose a non-conflicting port number
